### ISSUE TITLE
如何使用DreamArtist（++）？

### ISSUE THREAD

**Issue by syguan96** [7eu7d7/HCP-Diffusion-webui#7]
@7eu7d7 同学你好，这个工具很很简洁，非常好用。你好像没有把你的DreamArtist（++）集成进去，还是说我没看到？ 求指路

**Comment by benbenlike** [comment]
配置文件夹里有DA++的example哦

**Comment by syguan96** [comment]
我折腾了一下，由于缺乏文档，比较难上手。期待作者能够给一些guidance
